version: '3.8'

services:
  hardware_profile_1:
    build:
      dockerfile: HardwareProfile.Dockerfile
    ports:
      - "2222:22"
  
  postgres:
    image: postgres:latest
    container_name: postgres_quafel_web
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
