services:
  postgres:
    image: postgres:latest
    container_name: postgres_quafel_web
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hardware_profile_1:
    build:
      dockerfile: dockerfile/HardwareProfile.Dockerfile
    ports:
      - "2222:22"

  output_server:
    build:
      dockerfile: dockerfile/OutputServer.Dockerfile
    ports:
      - "2223:22"

  webapp_server:
    build:
      dockerfile: dockerfile/Webapp.Dockerfile
    ports:
      - "8000:8000"

volumes:
  postgres_data:
