services:
  postgres:
    image: postgres:latest
    container_name: postgres_quafel_web
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hardware.profile:
    build:
      dockerfile: dockerfile/HardwareProfile.Dockerfile
    ports:
      - "2222:22"
    depends_on:
      - output.server

  output.server:
    build:
      dockerfile: dockerfile/OutputServer.Dockerfile
    ports:
      - "2223:22"

  webapp.server:
    build:
      dockerfile: dockerfile/Webapp.Dockerfile
    ports:
      - "2224:22"
      - "8000:8000"
    volumes:
    # enables django hot-reloading
      - ./quafelweb:/app/quafelweb
    depends_on:
      - postgres
      - hardware.profile
      - output.server

volumes:
  postgres_data:
