# Generated by Django 5.0.6 on 2024-06-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareProfile',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('connection', models.CharField(max_length=100)),
            ],
        ),
    ]
