# Generated by Django 5.0.6 on 2024-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareProfile',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('protocol', models.CharField(max_length=100)),
                ('ip_addr', models.GenericIPAddressField(default='240.0.0.0')),
                ('port_addr', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
