# Generated by Django 5.0.7 on 2024-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareprofile',
            name='needs_totp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hardwareprofile',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
