# Generated by Django 5.0.6 on 2024-07-12 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hardwareprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
