# Generated by Django 5.0.6 on 2024-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwareprofile',
            old_name='connection',
            new_name='protocol',
        ),
        migrations.AddField(
            model_name='hardwareprofile',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardwareprofile',
            name='ip_addr',
            field=models.GenericIPAddressField(default='240.0.0.0'),
        ),
        migrations.AddField(
            model_name='hardwareprofile',
            name='port_addr',
            field=models.IntegerField(default=0),
        ),
    ]
