# Generated by Django 5.0.7 on 2024-07-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_controller', '0002_hardwareprofile_needs_totp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareprofile',
            name='ip_addr',
            field=models.CharField(default=''),
        ),
    ]
