# Generated by Django 5.0.7 on 2024-07-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_controller', '0003_alter_hardwareprofile_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareprofile',
            name='ip_addr',
            field=models.GenericIPAddressField(default='240.0.0.0'),
        ),
    ]
