# Generated by Django 5.0.6 on 2024-06-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware_controller', '0002_rename_connection_hardwareprofile_protocol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('shots', models.IntegerField()),
                ('qbits', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('evals', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('expressability', models.FloatField()),
                ('entangelment_cap', models.FloatField()),
                ('durations', models.FloatField(max_length=100)),
                ('hardware_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_controller.hardwareprofile')),
                ('simulator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation_data.simulatorprofile')),
            ],
        ),
    ]
