# Generated by Django 5.0.7 on 2024-09-24 19:10

import django.contrib.postgres.fields
import django.db.models.deletion
import quafel_simulators.base.simulator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hardware_controller", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulatorProfile",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            bases=(models.Model, quafel_simulators.base.simulator.QuafelSimulatorBase),
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("user", models.CharField(default="", max_length=100)),
                ("shots", models.IntegerField()),
                ("qubits", models.IntegerField()),
                ("depth", models.IntegerField()),
                ("finished", models.BooleanField(default=False)),
                ("expressibility", models.FloatField(default=0.0)),
                ("entangling_capability", models.FloatField(default=0.0)),
                (
                    "durations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=100
                    ),
                ),
                ("duration_avg", models.FloatField(default=0.0)),
                (
                    "hardware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware_controller.hardwareprofile",
                    ),
                ),
                (
                    "simulator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulation_data.simulatorprofile",
                    ),
                ),
            ],
        ),
    ]
