# Generated by Django 5.0.6 on 2024-06-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation_controller', '0001_initial'),
        ('simulation_data', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('requested_runs', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='simulation_data.simulationrun')),
            ],
        ),
        migrations.DeleteModel(
            name='SimulatorProfile',
        ),
    ]
