name: Check CodeStyle

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  pylint:
    name: Check CodeStyle with pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Ensure pip
      run: python -m ensurepip --upgrade

    - name: Install pylint
      run: pip install pylint

    - name: Run pylint
      run: pylint --rcfile=$GITHUB_WORKSPACE/.pylintrc **/*.py
