name: Check CodeStyle

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  pylint:
    name: Check CodeStyle with PyLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Install pylint
      run: sudo apt-get update && sudo apt-get install -y pylint

    - name: Verify .pylintrc presence
      run: ls -la
    
    - name: Run pylint
      run: |
        pylint_output=$(mktemp)
        pylint **/*.py > "$pylint_output" 2>&1
        cat "$pylint_output"
        # Fail the job if pylint found any issues
        grep -q "Your code has been rated at" "$pylint_output" || exit 20202
