name: GithubAction
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check_code_style:
    runs-on: ubuntu-latest
    name: Checking Code Style
    steps:
      - name: EditorConfigCheck
        uses: wow-rp-addons/actions-editorconfig-check@v1.0.1
