name: Check Code Style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v3
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v3
      - uses: notdevcody/intellij-format-action@v1.1
        with:
          style-settings-file: .codestyle.xml
          commit-on-changes: false
          fail-on-changes: true