name: GithubAction
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check_code_style:
    runs-on: ubuntu-latest
    name: Checking Code Style with the .editorconfig file
    steps:
      - name: running
        uses: zbeekman/EditorConfig-Action@v1.1.1
